### PR TITLE
Fix: Use RFC3339 Timestamp Format and Add Missing Fields in GitHub CheckRun Payload

### LINKED ISSUE #388: Bug: GitHub CheckRun Notification Fails Due to Invalid Timestamp Format and Missing Fields
## Summary

This issue concerns the `argocd-notifications` GitHub CheckRun integration.

When sending CheckRun notifications to GitHub, the controller fails due to two main problems:

1. Incorrect time parsing format for the `started_at` and `completed_at` fields.
2. Missing fields (`status` and `conclusion`) in the CheckRun payload, even though they are specified in the notification template.

### 1. Timestamp parsing error

- The controller attempts to parse the started_at and completed_at fields using the following invalid layout: `"YYYY-MM-DDTHH:MM:SSZ"`
- This is not compatible with Go's time.Parse() function, which expects a layout like time.RFC3339

Logs output: 

```logs
{"level":"error","msg":"Failed to notify recipient {github } defined in resource argocd/guestbook: parsing time \"2025-07-10T07:46:07Z\" as \"YYYY-MM-DDTHH:MM:SSZ\": cannot parse \"2025-07-10T07:46:07Z\" as \"YYYY-MM-DDTHH:MM:SSZ\" using the configuration in namespace argocd","resource":"argocd/guestbook","time":"2025-07-11T08:12:25Z"}
```

### 2. Missing Fields that exists in the payload:`status` and `conclusion`

- Even though the status and conclusion values are defined in the notification template, they were not passed through to the GitHub API payload, leading to a validation failure.

Logs:

```bash
{"level":"error","msg":"Failed to notify recipient {github } defined in resource argocd/guestbook: POST https://api.github.com/repos/mahdibouaziz/argo-lab/check-runs: 422 Validation Failed [{Resource:CheckRun Field:conclusion Code:missing_field Message:}] using the configuration in namespace argocd","resource":"argocd/guestbook","time":"2025-07-11T13:49:28Z"}
```

### Configured Template Example

Below is the relevant portion of the argocd-notifications-cm.yaml template being used:

```yaml
  template.github-app-deploy-notification: |
    message: |
      Application {{.app.metadata.name}} is now running new version of deployments manifests.
    github:
      status:
        state: success
        label: "argo-cd/{{.app.metadata.name}}"
      checkRun:
        name: "continuous-delivery/{{.app.metadata.name}}"
        details_url: "https://6fb99af6d16c.ngrok-free.app/applications/{{.app.metadata.name}}?operation=true"
        status: completed
        conclusion: success
        started_at: "{{.app.status.operationState.startedAt}}"
        completed_at: "{{.app.status.operationState.finishedAt}}"
        output:
          title: "Deployment of {{.app.metadata.name}} on ArgoCD"
          summary: "Application {{.app.metadata.name}} is now running new version of deployments manifests."
          text: |
            Application {{.app.metadata.name}} is now running new version of deployments manifests.
            See more here: https://6fb99af6d16c.ngrok-free.app/applications/{{.app.metadata.name}}?operation=true
```

## Expected Behavior

- The controller should correctly parse timestamps using `time.RFC3339`.
- The`status` and `conclusion` fields should be included in the payload sent to GitHub.

### PR DESCRIPTION
**Pull request by mahdibouaziz**
##  PR Description

This PR addresses [Issue #388](https://github.com/argoproj/notifications-engine/issues/388), which affects GitHub CheckRun notifications in `argocd-notifications`.

Two problems were identified:
1.`started_at` and `completed_at` fields failed to parse due to an incorrect time layout.
2. The `status` and `conclusion` fields were omitted from the GitHub CheckRun payload, causing validation errors.

## Fix Details

- Replaced the hardcoded invalid time layout `"YYYY-MM-DDTHH:MM:SSZ"` with the standard `time.RFC3339` layout for parsing `started_at` and `completed_at`.
- Explicitly included the `status` and `conclusion` fields in the payload sent to the GitHub CheckRun API.

## Impact

This fix ensures that GitHub CheckRun notifications are correctly formatted and accepted by GitHub, restoring proper CI/CD deployment reporting.

Fixes #388

### CODE REVIEW

File: pkg/services/github.go [hunk 1]
```diff
@@ -687,6 +687,8 @@ func (g gitHubService) Send(notification Notification, _ Destination) error {
 				ExternalID:  &externalID,
 				Name:        notification.GitHub.CheckRun.Name,
 				DetailsURL:  &notification.GitHub.CheckRun.DetailsURL,
+				Status:      &notification.GitHub.CheckRun.Status,
+				Conclusion:  &notification.GitHub.CheckRun.Conclusion,
```
Comment (evheniyt-pillar) [inline pkg/services/github.go]: the same here, need to make sure it can work when `Conclusion` is not set, because:
```
Required if you provide completed_at or a status of completed. The final conclusion of the check. Note: Providing conclusion will automatically set the status parameter to completed. You cannot change a check run conclusion to stale, only GitHub can set this.

```

File: pkg/services/github.go [hunk 2]
```diff
@@ -708,16 +708,42 @@ func (g gitHubService) Send(notification Notification, _ Destination) error {
...
+		conclusion := notification.GitHub.CheckRun.Conclusion
+
+		if conclusion != "" && status == "" {
+			status = "completed"
 		}
-		completedTime, err := time.Parse("YYYY-MM-DDTHH:MM:SSZ", notification.GitHub.CheckRun.CompletedAt)
-		if err != nil {
-			return err
+
+		if (status == "completed" || notification.GitHub.CheckRun.CompletedAt != "") && conclusion == "" {
```
Comment (pasha-codefresh) [inline pkg/services/github.go:718]: It will fail all time when status is completed, are you sure that this is expected?

**Comment by pasha-codefresh** [comment]
@mahdibouaziz one comment from my side and we are good to go

File: pkg/services/github.go (hunk 2 above)
Comment (mahdibouaziz) [reply pkg/services/github.go:718]: Yes, the early return is intentional to match the Checks API: Github requires`conclusion` whenever`status` is`completed` or`completed_at` is present (see docs here: https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#update-a-check-run). If we allow it through, Github responds with 422.
Screenshot 2026-02-14 at 11 35 37

As the docs note, when `status=completed` or `completed_at` is set, the payload must include`conclusion`.
